name = "uptimeflare"
main = "worker/index.ts"
compatibility_date = "2024-12-04"
compatibility_flags = ["nodejs_compat"]

# KV 绑定
[[kv_namespaces]]
binding = "STATE"
id = "b2fc927cdc094cb880dfc1e08bb006af"

# 定时触发器 - 每分钟执行一次监控
[triggers]
crons = ["* * * * *"]
